### ISSUE TITLE
Connection from VDDA and VSSA to VDD and VSS?

### ISSUE THREAD

**Issue by dumle29** [kiibohd/pcb#2]
Hey there. I'm working with a smaller chip, though quite identical to the one you are using on the IC60, and poking around the reference manual, it's stated that VSSA and VDDA should be connected to VDD and VSS if the analog supply pins are externaly available, with apropriate filtering, however it seems they are left unconnected on the IC60. Any reasons behind this?

**Comment by haata** [comment]
Basically, we don't use any analog features on our current set of keyboards so we can just leave them as disconnected, this way we don't need any filtering caps.

On future keyboards if we do something like a capsense controller we'll need to add proper reference voltages.

**Comment by dumle29** [comment]
Gotcha. Thanks for the answer :) These reference manuals are quite large, and your schematic helps a bunch to know where to look :)
