### ISSUE TITLE
What license are these released under?

### ISSUE THREAD

**Issue by spuder** [kiibohd/pcb#3]
I'm helping to design an opensource keyboard that works with both cherry mx and matias switches. 

Before I copy the dimensions from one of the footprints, I want to find out

- Is taking a footprint from the library in the ergodox infinity library fair use? 
- What license are these designs released under? 

Specifically I want to copy these two dimensions in the MXALPS footprint

<img width="902" alt="screenshot 2016-01-18 17 37 03" src="https://cloud.githubusercontent.com/assets/242382/12406655/377b7eea-be0c-11e5-86bc-9d7be769653d.png">
<img width="901" alt="screenshot 2016-01-18 17 36 55" src="https://cloud.githubusercontent.com/assets/242382/12406656/38fd5e1e-be0c-11e5-82b5-5f9a69370098.png">

<img width="674" alt="screenshot 2016-01-18 17 55 59" src="https://cloud.githubusercontent.com/assets/242382/12406708/cb50d692-be0c-11e5-9d43-11b87a8cc158.png">

The keyboard I'm working on will be released under the GPL license.

**Comment by parak** [comment]
The projects are under the CERN license, which should be in the root of the project folder as the LICENSE file. Hope that helps!

**Comment by spuder** [comment]
Great, thanks
