### ISSUE TITLE
PCB STEP file?

### ISSUE THREAD

**Issue by Sqwrly** [kiibohd/pcb#4]
Hello, hopefully this is the right place to put this. Is it possible to have a STEP file of the IC60? I would prefer the new revision but any is fine really.

Thanks.

**Comment by parak** [comment]
Hiya - KiCad is not that great at exporting STEP, so the best one might do without spending a lot of time on it is a simple blank shape with holes. I think I might have one of those around, generated with kicad stepup script. If you are looking for components being placed on it as well, that's not something that I've done, but you can do yourself if you want to with the same kicad stepup script (just takes a while).

**Comment by Sqwrly** [comment]
Hey Parak, I actually got what I was looking for through another channel but I'm still sure other people would appreciate having access to what I was looking for. I'm personally happy with just the PCB shape with holes. I don't really need the components to be placed on it.
