### ISSUE TITLE
via from the anode of D66 to D56/D51 appears to have been misaligned (or the trace failed somewhere along there)

### ISSUE THREAD

**Issue by dondelelcaro** [kiibohd/pcb#6]
Just in case someone else has this problem: on my right hand board (Infinity Ergodox), the via from the anode of D66 to D56/D51 appears to have been misaligned (or the trace failed somewhere along there). This will show up with D66 and D75 not working at all even if they are installed with the correct polarity. Bypassing this trace seems to clear up the issue pretty easily.

I looked at the gerbers, and I couldn't see anything wrong, so I'm guessing that this is a one off manufacturing issue, but wanted to see what you thought.

**Comment by parak** [comment]
Do you happen to have any visual indications that something is wrong there, or is it simply not working? This is the first report that I've heard of this, so a one-off is possible, although the fab is supposed to be doing etests on each board for broken traces...

**Comment by dondelelcaro** [comment]
Simply not working; I looked at the board and didn't see anything obviously wrong. There's just a discontinuity somewhere along that trace. [Though of course, I started checking this out after I had populated the board; it's possible that there is something wrong that I just can't see or don't have the experience to notice.]



![keyboard](https://cloud.githubusercontent.com/assets/1300008/14963284/7dc1e368-1068-11e6-9eda-89631e696dad.jpg)

**Comment by haata** [comment]
Hmm, I've had this happen to me during the early Infinity Ergodox
prototypes when I was quickly desoldering and pulling out LEDs. If you're
too forceful, some of the traces can pull out...

**Comment by dondelelcaro** [comment]
Yeah, I would normally guess that too, but it was failed even before I de-soldered them. [I just assumed I had momentarily not been paying attention and screwed up the LED polarity... but testing with a multimeter when the replacements failed the same way clued me in.]

Anyway, sounds like this is probably just a one-off manufacturing failure. I guess if someone else has the same failure, they can re-open and/or comment. [Thanks for adding mouse support just recently, BTW! Was not looking forward to figuring out how to add that myself.]
